# Generated by Django 6.0.2 on 2026-02-06 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la salle')),
                ('capacite', models.PositiveIntegerField(verbose_name='Capacité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('localisation', models.CharField(blank=True, max_length=200, verbose_name='Localisation (étage, bâtiment, etc.)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la session')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('nombre_participants', models.PositiveIntegerField(verbose_name='Nombre de participants attendus')),
                ('formateur', models.CharField(max_length=100, verbose_name='Formateur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formation.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(fields=('salle', 'date_debut', 'date_fin'), name='unique_salle_créneau')],
            },
        ),
    ]
